# Generated by Django 4.1.7 on 2023-05-22 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('genero_musical', models.CharField(max_length=50)),
                ('correo_contacto', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('cedula', models.CharField(max_length=10)),
                ('correo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Concierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('artista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='artista', to='Concert.artista')),
            ],
        ),
        migrations.CreateModel(
            name='Escenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nro_disponibles', models.IntegerField(default=0)),
                ('precio', models.FloatField(default=0)),
                ('estado', models.BooleanField(default=True)),
                ('concierto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidad_concierto', to='Concert.concierto')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('nro_tickets', models.SmallIntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cliente', to='Concert.cliente')),
                ('concierto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='concierto', to='Concert.concierto')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localidad', to='Concert.localidad')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('total', models.FloatField(default=0)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserva', to='Concert.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='concierto',
            name='escenario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escenario', to='Concert.escenario'),
        ),
    ]
