# Generated by Django 4.1.7 on 2023-05-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='total_compra',
            field=models.FloatField(default=0),
        ),
    ]
