# Generated by Django 4.1.7 on 2023-05-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Concert', '0002_reserva_total_compra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
